### ISSUE TITLE
todo list monoticket

### ISSUE THREAD

**Issue by mitchellwrosen** [mitchellwrosen/libzmq#1]
- [ ] add draft api
- [ ] libzmq tests
- [ ] CInt -> Int some re-exported patterns in libzmq
- [ ] Int -> CInt conversions are sketchy
- [ ] confirm free2 works
- [ ] rename Zmq_socket_events
- [ ] monomorphize zmq_setsockopt_storable
- [ ] ZMQ_ROUTER_NOTIFY options
